name: Update productive hours gist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update productive hours
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.PRODUCTIVE_BOX_TOKEN }}
          GIST_ID: ${{ secrets.PRODUCTIVE_BOX_GIST_ID }}
          TIMEZONE: ${{ vars.TIMEZONE }}
